image:
  repository: okteto.dev/rails-k8s-demo
  tag: prod

rails:
  replicaCount: 1

sidekiq:
  replicaCount: 1

redis:
  cluster:
    enabled: false
  usePassword: false
  master:
    disableCommands: []
