name: web
image: okteto/chat:dev
command: bash
sync:
  - .:/app
services:
  - name: sidekiq
    image: okteto/chat:dev
    sync:
      - .:/app
forward:
  - 1234:1234
  - 5234:db:5234
environment:
  - RAILS_ENV=development