name: web
image: okteto/chat:dev
command: bash
workdir: /app
forward:
  - 1234:1234
  - 5234:db:5234
services:
  - name: sidekiq
    image: okteto/chat:dev
    mountpath: /app
persistentVolume:
  enabled: true
