apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails-k8s-demo.fullname" . }}
  labels: {{- include "rails-k8s-demo.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rails-k8s-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
