apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  annotations:
    helm.sh/hook: pre-upgrade, pre-install
    helm.sh/hook-weight: "-1"
data:
  DATABASE_URL: postgresql://okteto:okteto@postgresql:5432/okteto
  REDIS_URL: redis://rails-k8s-demo-redis-master:6379/
