apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: {{ .Values.rails.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "rails-k8s-demo.serviceAccountName" . }}
      containers:
        - name: chat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - rails
          args:
            - "server"
            - "-b"
            - "0.0.0.0"
          envFrom:
          - configMapRef:
              name: common-env
